# Generated by Django 5.2 on 2025-06-29 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='utilisateur',
            name='role',
            field=models.CharField(blank=True, choices=[('magistrat', 'Magistrat'), ('greffier', 'Greffier'), ('secretaire', 'Secrétaire')], max_length=20, null=True),
        ),
    ]
