# Generated by Django 5.2 on 2025-07-01 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_utilisateur_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='utilisateur',
            name='profile_image',
            field=models.ImageField(blank=True, help_text='Photo de profile', null=True, upload_to='media/profile_images'),
        ),
    ]
