# Generated by Django 5.2 on 2025-06-29 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dossier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_dossier', models.CharField(help_text='Numéro unique du dossier', max_length=50, unique=True)),
                ('nom_affaire', models.CharField(help_text="Nom de l'affaire ou du litige", max_length=255)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('statut', models.CharField(choices=[('Ouvert', 'Ouvert'), ('Clos', 'Clos'), ('En attente', 'En attente')], default='ouvert', help_text='Statut actuel du dossier (ouvert, clos, en attente...)', max_length=50)),
                ('contact_partie', models.CharField(blank=True, help_text='Contact principal ou partie impliquée', max_length=255, null=True)),
                ('numero_telephone_partie', models.CharField(blank=True, help_text='Numéro de téléphone de la partie pour certaines notifications', max_length=20, null=True)),
            ],
            options={
                'verbose_name': 'Dossier',
                'verbose_name_plural': 'Dossiers',
                'ordering': ['-date_creation'],
            },
        ),
        migrations.CreateModel(
            name='EtapeDossier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_mise_a_jour', models.DateTimeField(auto_now_add=True, help_text='Date et heure de la mise à jour')),
                ('action_menee', models.TextField(help_text="Description détaillée de l'action menée ou de l'étape")),
                ('type_etape', models.CharField(choices=[('creation', 'Création'), ('modification', 'Modification'), ('consultation', 'Consultation'), ('audience', 'Audience'), ('depot_conclusion', 'Dépôt de conclusion'), ('jugement_rendu', 'Jugement rendu'), ('reouverture', 'Réouverture'), ('autre', 'Autre')], default='autre', help_text="Catégorie de l'action", max_length=50)),
            ],
            options={
                'verbose_name': 'Étape du Dossier',
                'verbose_name_plural': 'Historique des Étapes des Dossiers',
                'ordering': ['date_mise_a_jour'],
            },
        ),
    ]
