# Generated by Django 5.2 on 2025-06-29 11:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dossiers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='dossier',
            name='auteur',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='dossier',
            name='greffier_responsable',
            field=models.ForeignKey(help_text='Greffier assigné au dossier', limit_choices_to={'role': 'greffier'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dossiers_greffier', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='dossier',
            name='magistrat_responsable',
            field=models.ForeignKey(help_text='Magistrat en charge du dossier', limit_choices_to={'role': 'magistrat'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dossiers_magistrat', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='etapedossier',
            name='auteur',
            field=models.ForeignKey(help_text="Utilisateur ayant effectué l'action (auteur)", null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='etapedossier',
            name='dossier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='etapes', to='dossiers.dossier'),
        ),
    ]
