# Generated by Django 5.2 on 2025-06-29 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alerte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_type', models.CharField(choices=[('audience', 'Audience Fixée'), ('conclusion', 'Dépôt de Conclusion'), ('jugement', 'Jugement à Rendre')], help_text="Le type d'alerte prédéfini.", max_length=100)),
                ('description_type', models.TextField(blank=True, help_text="Description détaillée du type d'alerte.", null=True)),
                ('est_multiple', models.BooleanField(default=False, help_text="Cochez si cette alerte génère plusieurs notifications (ex: 48h et 12h avant l'événement).")),
                ('delai_jours', models.IntegerField(default=0, help_text="Nombre de jours de décalage par rapport à la date de l'événement initial (négatif si avant, positif si après).")),
                ('delai_heures', models.IntegerField(default=0, help_text="Nombre d'heures de décalage par rapport à la date de l'événement initial (négatif si avant, positif si après).")),
                ('date_evenement_initial', models.DateTimeField(blank=True, help_text="Date de l'événement principal (ex: date d'audience), utilisé pour calculer les déclenchements.", null=True)),
                ('date_declenchement_cible', models.DateTimeField(help_text='Date et heure exactes à laquelle cette alerte spécifique doit être envoyée.')),
                ('date_creation', models.DateTimeField(auto_now_add=True, help_text="Date et heure de création de l'alerte.")),
                ('message', models.TextField(blank=True, help_text="Message spécifique pour cette instance d'alerte. Si vide, un message par défaut sera généré.", null=True)),
                ('est_envoyee', models.BooleanField(default=False, help_text='Indique si la notification SMS a été envoyée pour cette alerte.')),
                ('date_envoi', models.DateTimeField(blank=True, help_text="Date et heure de l'envoi effectif de la notification SMS.", null=True)),
            ],
            options={
                'verbose_name': 'Alerte',
                'verbose_name_plural': 'Alertes',
                'ordering': ['date_declenchement_cible'],
            },
        ),
    ]
