# Generated by Django 5.2 on 2025-06-29 11:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('alerts', '0001_initial'),
        ('dossiers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='alerte',
            name='cree_par',
            field=models.ForeignKey(blank=True, help_text="L'utilisateur qui a créé cette alerte.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alertes_creees', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='alerte',
            name='destinataires',
            field=models.ManyToManyField(help_text='Utilisateurs spécifiques qui recevront cette alerte.', related_name='alertes_recues', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='alerte',
            name='dossier',
            field=models.ForeignKey(help_text='Le dossier auquel cette alerte est liée.', on_delete=django.db.models.deletion.CASCADE, related_name='alertes', to='dossiers.dossier'),
        ),
    ]
